BE/src/app.module.ts, BE/src/configs/typeorm.config.ts, BE/src/users/users.controller.ts, BE/src/users/users.dto.ts, BE/src/users/users.entity.ts, BE/src/users/users.module.ts, BE/src/users/users.repository.ts, BE/src/users/users.service.ts
- `/users` API로 POST 요청 시 user 테이블에 유저 정보 추가 
- password 저장 시 base64 `btoa()` 를 통한 비밀번호 암호화
- 이전에 엔티티를 통해 데이터베이스 테이블이 생성되지 않은 문제가 발생
- 파일명 수정 후 테이블 생성 확인
- users.controller, users.service, user.repository 구현
- `/users` 로 POST 요청 시 user 테이블에 추가
- `LoginUserDto` 생성
- createdData 데코레이터 등 datetime을 자동으로 설정했을 때 timezone이 한국이 아닌 상태로 추가됨
- Timezone을 Asia/Seoul로 설정
**[ Postman으로 API 실행 결과 ]**
- typeorm에서 create 명령은 실제로 데이터를 추가하지 않는다. save를 해야된다..!
- id는 에러가 나도 auto increment가 된다.
- repository 의존성 주입
- 비밀번호 암호화를 보안적으로 더 빡세게!
- 컨트롤러단에서 try-catch로 에러 검사 한번 더 하기
- userId가 존재하는지 확인하는 로직 추가?
- `createUserDto` → password를 암호화된 비밀번호와 상관없이 가져가는 것에 대한 처리?
close #15
=> [Feat] 회원가입 API 구현

BE/src/configs/typeorm.config.ts, BE/src/diaries/diaries.dto.ts, BE/src/diaries/diaries.entity.ts, BE/src/users/users.dto.ts, BE/src/users/users.entity.ts, BE/src/users/users.repository.ts
- Diary Entity 및 DTO 생성
- 아래와 같은 경고문구 발생
```
Ignoring invalid timezone passed to Connection: Asia/Seoul. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
```
- TypeORM timezone을 `Asia/Seoul` 에서 `+09:00`으로 변경해서 해결. 다른 형식이나 동일한 뜻을 가짐.
- `class-validator`를 활용하여 DTO 유효성 검사
- User Entity와 FK 설정
| 참고: https://typeorm.io/many-to-one-one-to-many-relations
```tsx
@ManyToOne(() => User, (user) => user.userId, { nullable: false })
user: User;
```
- 위와 같이 작성 시 자동으로 컬럼명이 userId로 입력됨
- User 엔티티에 해당 User가 작성한 diaries가 관리됨. 실제로 DB에 저장되지는 않으나 런타임 단계에서 꺼낼 수 있을 것으로 예상
- 통일을 위해서 `userID` → `userId` 로 네이밍 수정
- uuid는 `@Generated()` 데코레이터를 사용해 자동 생성
- 좌표 데이터는 string(1,2,3) 형식으로 저장
- 이에 해당하는 정규식 검사 추가
```tsx …
```
=> [Feat] Diary Entity 및 DTO 생성

BE/src/app.module.ts, BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.entity.ts, BE/src/diaries/diaries.module.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts, BE/src/utils/enum.ts
- Diary 코드 초기 템플릿 설정
- Diary Entity에 감정분석 컬럼 추가
- Controller, Service, Repository, Module 추가
- Enum sentimentStatus 정의
- positiveRatio, negativeRatio, neutralRatio를 float로 설정
- 감정분석 컬럼이 추가되면서 ERD 수정
close #30
=> [Feat] Diary 초기 코드 템플릿 및 감정분석 컬럼 추가

BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts
- /diaries POST 요청 처리
- diaries.controller, diaries.service에 writeDiary 메서드 구현
- diaries.repository에 DB에 일기 데이터를 저장하는 insertDiary 메서드 구현
- 일기의 content는 btoa()를 활용하여 base64로 암호화하여 저장
```
No overload matches this call.
Overload 1 of 3, '(this: (new () => Diary) & typeof BaseEntity, entityLikeArray: DeepPartial<Diary>[]): Diary[]', gave the following error.
Argument of type '{ title: string; content: string; point: string; date: Date; color: string; positiveRatio: number; negativeRatio: number; neutralRatio: number; sentiment: sentimentStatus; shape: number; user: { ...; }; }' is not assignable to parameter of type 'DeepPartial<Diary>[]'.
Object literal may only specify known properties, and 'title' does not exist in type 'DeepPartial<Diary>[]'.
Overload 2 of 3, '(this: (new () => Diary) & …
```
=> [Feat] 일기 생성 API 구현

BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts
- /diaries GET 요청 처리
- diaries.controller, diaries.service, diaries.repository에 readDiary 메서드 구현
- diaries.controller에서 클라이언트에 전달할 응답을 구성
- Get(":uuid")와 Get("/:uuid") 모두 동일하게 처리가 되는 것을 알아서, 명시적으로 Get("/:uuid") 으로 하도록 결정했습니다.
- ReadDiaryDto의 아이템이 uuid 1개밖에 없어서 그냥 uuid를 바로 사용할까 했으나 Dto로 주고받는 것이 더 코드 스타일 상 옳은 것 같아 Dto로 주고받도록 구현했습니다.
- conflict를 처음 마주쳤는데 생각보다 온건하게 처리가 되어서 다행이라고 생각했습니다..
close #38
=> [Feat] 일기 읽기 API 구현

BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts
- `/diaries/:uuid` DELETE 요청 처리
- diaries.controller, diaries.service에 deleteDiary 메서드 구현
- diaries.repository에 DB에 일기 데이터를 삭제하는 deleteDiary 메서드 구현
- soft delete 방식으로 삭제 → 올바른 uuid로 삭제 시 deletedDate 컬럼 값이 변경됨
- 이미 soft delete로 삭제된 값을 다시 삭제 시 error
**[테이블에서 일기 삭제 반영 결과]**
**[이미 soft delete로 삭제된 일기를 다시 삭제 시 응답]**
- 검색했을 때 Typeorm에서 제공한다고 하는 softDelete() 함수가 있다고 했는데 없었음..
- 따라서 softRemove()를 사용하고 이전에 getDiaryByUuid() 함수를 통해 해당하는 엔티티 레코드 찾음
close #43
=> [Feat] 일기 삭제 DELETE API 구현

BE/src/configs/typeorm.config.ts, BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.service.ts, BE/test/app.e2e-spec.ts, BE/test/jest-e2e.json
- 일기 API CRUD e2e 테스트 코드 작성
- Date 객체 시간을 KST로 변환
- jest 초기 세팅 진행
- 각 테스트가 독립되어 돌아가기 위해 데이터를 생성 후 삭제하도록 구현
- 현재는 config 파일에서 실제 DB와 통신
- READ: response.body가 아닌 response.text에 값이 들어가있음
- mysql 서버 시간은 KST로 되어있지만, typeorm에서 가져올 때 자동으로 UTC로 변환되어 가져옴
- 서비스 단에서 직접 9시간을 더해주어 반환
- DTO에서 undefined를 검사해주지 않아 수정 필요
- 현재는 config 파일에서 실제 DB와 통신 -> Test 데이터베이스로 변경 필요
close #42
=> [Feat] 일기 API CRUD e2e 테스트 코드 작성

.github/workflows/deploy.yml, BE/src/main.ts
- BE 배포 스크립트 작성
- FE 배포 스크립트 작성
- NCloud VPC에 정상적으로 동작하도록 구현
- SSH로 직접 서버에 접속하여 프로젝트 폴더로 이동 후 pull하는 방식으로 배포했다.
- BE와 FE가 실행될 때 포트 번호를 다르게 해주어야 해서 BE의 포트 번호를 변경했다.
- BE 배포가 진행될 때 기존의 BE, FE 서버를 종료하기 위해 killall node를 수행한다.
- BE와 동일하나 needs를 추가하여 BE 배포가 완료된 후에 배포하도록 설정했다.
- NCloud VPC에 스크립트와 동일한 동작을 하여 서버에 제대로 접근이 되나 테스트했다.
- npm restart는 기존과 다른 터미널에서 실행 시 포트 겹침 문제가 있었다. 따라서 killall node를 통해 nodejs로 실행중인 프로세스를 모두 종료한 후 BE 실행 -> FE 실행 순으로 스크립트를 작성했다.
close #50
=> [Deploy] Github Action을 통한 CI/CD 구축

.github/workflows/deploy.yml
- 배포 스크립트 오류 수정
- 기존에는 npm start로 FE, BE 서버를 실행하도록 하였기 때문에 포어그라운드에서 두 서버가 모두 실행될 수 없어 오류가 발생했습니다.
- 현재는 nohup을 사용하여 백그라운드에서 두 서버가 실행되도록 하여 오류를 수정했습니다.
- 기존에는 killall node를 통해 동작중인 서버를 중지하도록 했지만 현재는 fuser -k를 사용하여 FE, BE 포트 각각에 대해서 중지하도록 만들었습니다.
- </dev/null은 입력을 받지 않도록, >/dev/null은 출력을 받지 않도록 하는 옵션입니다.
- 2>&1은 프로그램의 에러를 출력으로 받는 것이나, >/dev/null로 인해 무시됩니다.
- 마지막 &를 붙이면 해당 프로세스를 백그라운드에서 실행하도록 합니다. 
close #59
=> [Hotfix] 배포 스크립트 오류 수정

BE/src/auth/auth.id-guard.ts, BE/src/auth/auth.module.ts, BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.entity.ts
- 타인의 일기에 대한 접근을 막는 IdGuard 구현
- 일기 API에 IdGuard 적용
- 현재 요청한 유저의 userId값과 요청한 일기의 user.userId값이 일치하는지 확인하여 접근을 허용합니다.
- GET과 DELETE의 경우 url 파라미터로, PUT의 경우 body에 담아서 userId를 전달하기 때문에 삼항 연산자를 통해 상황에 맞게 적용될 수 있도록 만들었습니다.
- 자신이 작성한 일기에 정상적으로 접근 시 올바른 값을 리턴합니다.
- 타인의 일기에 접근 시 404 Not Found 에러를 응답합니다. 
- 일기 API 중 타인의 접근을 막아야 하는 Read, Update, Delete에 대해 IdGuard 적용
- 일기 Create의 경우 타인의 userId로 생성이 불가능하기 때문에 비로그인 상태 접근만 막으면 됨
- diary.dto.ts에서 ManyToOne 관계를 맺고 있는 user, shape에게 eager: true 옵션을 넣었습니다. 
- eager 옵션은 외래 키 관계를 맺은 해당 테이블을 eager loading하여 find 등의 메서드를 사용할 때 이 칼럼도 같이 join 시켜서 리턴하는 역할을 하게 됩니다. 
close #62
=> [Feat] 타인의 일기 관련 기능에 대한 접근 막기

BE/src/diaries/diaries.dto.ts, BE/src/diaries/diaries.entity.ts, BE/src/diaries/diaries.module.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts, BE/src/tags/tags.controller.ts, BE/src/tags/tags.entity.ts, BE/src/tags/tags.module.ts, BE/src/tags/tags.repository.ts, BE/src/tags/tags.service.ts
- 태그 기능을 위한 tags 디렉토리의 파일 구현
- ManyToMany 관계 설정 주체를 tags.entity에서 diaries.entity로 변경
- 일기 CREATE시 태그를 받아 저장하도록 추가
- 현재 사용하지 않는 tags.module, tags.controller, tags.service를 구현한 이유는 추후 일기 필터링 및 통계 기능을 위한 틀을 잡기 위함
- tags.repository에 태그 엔티티를 생성하여 저장하는 createTag 메서드 구현 
- ManyToMany 관계 설정은 두 엔티티 중 더 중요하다고 생각되는 쪽에 붙여야 한다.
- 특히나 우리 서비스의 경우 Diary를 읽었을 때 그 안의 Tag까지 읽어와야 하기 때문에 Diary 쪽에 ManyToMany 관계 설정을 하도록 수정했다
- 기존에는 Diary를 읽었을 때에는 어떤 Tag가 연결되었는지 보이지 않고, Tag를 읽으면 연결된 Diary가 보이는 구조였다.
- createDiaryDto에 태그명을 전달받기 위한 string 타입 배열 tags를 추가
- diaries.service의 writeDiary에서 tags.repository를 import하여 tags에 있는 태그명을 통해 Tag 엔티티를 생성하여 배열에 저장한 후 diaries.repository에 넘겨줌
- tags의 태그명을 기준으로 findOne을 통해 해당 태그가 존재하는지 확인한다. 
- 태그가 이미 존재하는 경우 해당 태그를 findOneBy로 가져오고, 없는 경우에만 createTag를 통해 태그 엔티티를 생성한다
close #65
=> [Feat] 태그 기능 구현

FE/public/data/data.json, FE/src/components/DiaryModal/DiaryReadModal.js, FE/src/index.js
- 일기 읽기 모달에 대해 일기 목업 데이터 작성 및 연결
- public 폴더 내 일기 API 목업 데이터 작성
- 최상위 컴포넌트를 ueryClientProvider로 감싸줌
- 일기 읽기 모달 내에서 목업 데이터 연동
- 리액트 쿼리로 데이터를 받아올 때 로딩 및 에러 UI를 구현하면 어떨까?
- 리액트 hooks를 모두 컴포넌트 반환 전에 선언해야 한다.
```js
if (isLoading) return <div>로딩중...</div>;
if (isError) return <div>에러가 발생했습니다</div>;
const [diaryState, setDiaryState] = useRecoilState(diaryAtom);
```
위와 같이 선언하면 에러가 발생한다. 따라서 다음과 같이 수정해야 함.
```js
// 모든 hooks는 반환 전에 선언할 것
const [diaryState, setDiaryState] = useRecoilState(diaryAtom);
const { data, isLoading, isError } = useQuery("diary", getDiary);
if (isLoading) return <div>로딩중...</div>;
if (isError) return <div>에러가 발생했습니다</div>;
```
close #27
=> [Feat] 일기 목업 데이터 작성 및 연결

BE/src/app.module.ts, BE/src/auth/get-user.decorator.ts, BE/src/shapes/shapes.controller.ts, BE/src/shapes/shapes.default.ts, BE/src/shapes/shapes.entity.ts, BE/src/shapes/shapes.module.ts, BE/src/shapes/shapes.repository.ts, BE/src/shapes/shapes.service.ts
- `/shapes/default` GET 요청 처리 시 해당하는 Shape 객체 배열 반환
- `/shapes/:uuid` GET 요청 처리 시 해당하는 모양 스트림 반환
- `GetUser` 데코레이터 추가
- 이전에 PR #57 에서 생성해주신 NCP Object Storage 버킷에 테스트 모양 이미지 3개 저장
- Content-Type을 `image/png`로 지정 
- 백엔드 서버를 실행시킬 때마다 Shape 테이블에 기본 모양에 대한 데이터 저장 
- `AppModule`에서 `commonUser` 생성 후 User 정보로 추가
- 기본 모양 데이터를 Shape 테이블에 추가
- 이미 유저가 있거나, 모양 데이터 파일이 있다면 생성하지 않음
- `shapes.controller`에서 `shapes/default` GET 요청을 받아 해당하는 Shape 객체 배열 반환
- 로그인 상태(인증)와 상관없이 결과를 반환
**[ shapes/default GET 요청 실행 결과 ]**
> Entities in lazy relations are loaded once you access them. Such relations must have Promise as type - you store your value in a promise, and when you load them a promise is returned as well.
> Lazy relations:  https://typeorm.io/eager-and-lazy-relations
- Shape Entity의 user 컬럼에 대해 **Lazy …
=> [Feat] 기본 모양 객체 응답 및 uuid에 해당하는 모양 스트림 반환 API 구현

BE/src/app.module.ts, BE/src/configs/typeorm.config.ts, BE/src/diaries/diaries.dto.ts, BE/src/diaries/diaries.entity.ts, BE/src/diaries/diaries.repository.ts, BE/src/main.ts, BE/src/users/users.dto.ts, BE/src/users/users.entity.ts
- 사용자 엔티티, DTO 업데이트
- 일기 엔티티, DTO 업데이트
- DB synchronize false로 수정
- CORS 정책 위반 오류 해결
- CreateUserDto, LoginUserDto에 Length를 적절하게 수정
- CreateuserDto에 email 추가. email을 위한 정규표현식 Matches도 작성 완료
- CreateDiaryDto, UpdateDiaryDto에 shapeUuid 추가
- 일기 엔티티에 color 제거
- 수정 사항에 맞게 diaries.repository, app.module 업데이트
- DB synchronize를 false로 하여 더 이상 구조 수정이 안되도록 변경
- enableCors 함수를 통해 CORS 정책 허용
- 별숲 노션의 API 문서
close #76
=> [Refactor] 사용자와 일기에 대한 엔티티, DTO 업데이트

BE/src/users/users.repository.ts
- getUserByUserId 처리 수정
- 아래와 같이 변경하여 app.module.ts 부분에서 유저가 없는 경우에 대한 처리가 잘 되도록 변경
```ts
async getUserByUserId(userId: string): Promise<User> {
return found = await User.findOne({ where: { userId } });
}
```
close #75
=> [Hotfix] 마스터 유저 생성 실패 오류 

BE/src/diaries/diaries.service.ts
- 일기 생성 시 태그 관련 동작에 비동기 처리 추가
- 일기를 생성하는 writeDiary에서 태그명을 받아 태그 객체를 생성하거나 불러오는 코드에 비동기 처리를 추가하여 태그가 누락되지 않도록 함
- forEach나 map 등의 경우 async / await으로 비동기 처리가 되지 않기 때문에 Promise.all()로 묶어 await을 붙이도록 수정함 
close #93
=> [Fix] 일기 생성 시 태그 관련 동작에 비동기 처리 추가

FE/public/data/data.json, FE/src/atoms/diaryAtom.js, FE/src/atoms/headerAtom.js, FE/src/components/DiaryModal/DiaryDeleteModal.js, FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryReadModal.js, FE/src/components/Header/Header.js, FE/src/components/SideBar/SideBar.js, FE/src/pages/MainPage.js
- 일기 나열 페이지 UI 구현
- 목업 데이터를 일기 데이터 배열으로 변경
- 일기 나열 페이지 UI 구현
- Atom에 나열 페이지 상태 추가
- 나열 페이지 상태 수정 이벤트 추가
- prev를 활용한 상태 수정 이벤트 가독성 향상
- 추후 나열 페이지 필터 구현 필요
close #87
=> [Feat] 일기 나열 페이지 UI 구현

FE/src/assets/zoomIn.svg, FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryReadModal.js, FE/src/styles/Modal/ModalWrapper.js
- 일기 나열 페이지 API 연동
- 모든 모달에 대해 배경색 투명도 0.3으로 통일
- react-query 활용 일기 전체 조회 API 연동
- 일기 줌인 버튼 추가
- 추후 디자인 수정 필요
close #95
=> [Feat] 일기 나열 페이지 API 연동

BE/src/auth/auth.module.ts, BE/src/auth/guard/auth.diary-guard.ts, BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.dto.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts, BE/test/diaries.delete.e2e-spec.ts
- 일기 삭제 API 응답 수정
- 일기 삭제 e2e 테스트 작성
- 일기 정상 삭제 시 204 No Content 응답
- 액세스 토큰 없이 요청 시 401 Unauthorized 응답
- 타인의 일기에 대해 요청 시 404 Not Found 응답
- 존재하지 않는 일기에 대해 요청 시 404 Not Found 응답
- 정상 요청 시 200 OK 응답하는 e2e 테스트 코드 작성
- 액세스 토큰 없이 요청 시 401 Unauthorized 응답하는 e2e 테스트 코드 작성
- 존재하지 않는 일기에 대한 요청 시 404 Not Found 응답하는 e2e 테스트 코드 작성
정상 요청 시 200 OK 응답
액세스 토큰 없이 요청 시 401 Unauthorized 응답
존재하지 않는 일기에 대한 요청 시 404 Not Found 응답
타인의 일기에 대해 요청 시 404 Not Found 응답
#96
=> [Feat] 일기 삭제 API에 대한 서버 응답 수정 및 e2e 테스트 작성

FE/public/data/data.json, FE/src/atoms/diaryAtom.js, FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryReadModal.js
- 기존에 구현한 읽기 모달 그대로 재사용
- 리스트 보기 로직 변경
- 각 다이어리 선택 시 diaryAtom에 해당 게시글 uuid 저장
- 자세히 보기 클릭 시 리스트보기를 닫고 읽기 모달 열기
- 읽기 모달 데이터 연결 로직 변경
- 읽기 모달이 열릴 때마다 uuid를 통해 일기를 다시 요청하고 해당 내용을 출력
- 테스트용 data.json을 API 문서 형식에 맞게 수정하였음.
close #97
=> [Feat] 리스트 보기에서 자세히 보기 버튼 클릭 시 읽기 모달 연결

FE/src/components/DiaryModal/DiaryDeleteModal.js, FE/src/pages/MainPage.js
- 일기 삭제 API 연동
https://github.com/boostcampwm2023/web08-ByeolSoop/assets/67178684/b98e0c4d-0811-4f38-acd7-3af18aa211b3
- 메인 페이지 클릭 시 일기 생성 모달 표시하도록 변경
- react-query 활용 일기 삭제 API 연동
- 추후 전체 일기 정보를 가져오는 함수를 메인 페이지에서 실행하도록 수정해야 함
- 일기가 없을 경우, 일기 나열 가장 오른쪽 모달을 띄우지 말아야 할 듯
close #99
=> [Feat] 일기 삭제 API 연동

FE/src/atoms/diaryAtom.js, FE/src/components/DiaryModal/DiaryCreateModal.js, FE/src/components/DiaryModal/DiaryLoadingModal.js, FE/src/pages/MainPage.js, FE/src/styles/Modal/LoadingAnimation.js
- 일기 로딩 애니메이션 구현
https://github.com/boostcampwm2023/web08-ByeolSoop/assets/67178684/603c2870-4839-4bed-a8e7-dff70daffe59
- diaryAtom에 로딩 모달 상태 관리 추가
- styles 폴더 내 로딩 애니메이션 CSS 작성
- 일기 로딩 모달 UI 작성
- 상태 수정을 통한 로딩 모달 표시
- 추후 일기 생성 성공 시 3초, 일기 생성 실패 시 무한 로딩 구현할 것
close #109
=> [Feat] 일기 로딩 애니메이션 구현

BE/src/auth/guard/auth.diary-guard.ts, BE/src/auth/guard/auth.jwt-guard.ts, BE/src/auth/jwt.strategy.ts, BE/src/diaries/diaries.controller.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts, BE/src/diaries/dto/diaries.dto.ts, BE/src/shapes/shapes.controller.ts, BE/test/diaries.update.e2e-spec.ts, BE/test/e2e/auth.signin.e2e-spec.ts, BE/test/e2e/diaries.create.e2e-spec.ts, BE/test/e2e/diaries.delete.e2e-spec.ts, BE/test/e2e/diaries.read-list.e2e-spec.ts, BE/test/e2e/diaries.read.e2e-spec.ts, BE/test/e2e/diaries.update.e2e-spec.ts
- 일기 수정 및 수정 API에 대한 서버 응답 수정 
- `UpdateDiaryDto` 수정
- `AuthGuard`를 상속받은 커스텀 `JwtAuthGuard` 구현 
- Fix: 일기 작성할 때 DTO에 저장된 shape, 로그인한 유저 정보를 올바르게 저장
- `@GetUser` 데코레이터를 사용하여 User 정보 가져오도록 추가
- `shapeUuid`에 해당하는 shape 객체 추가
- `UpdateDiaryDto`가 `CreateDiaryDto`를 상속받도록 수정
- `CreateDiaryDto`에서 `uuid`가 추가된 형태이기 때문에 상속으로 중복된 부분 처리
- `uuid`에 대한 데이터 유효성 검사 추가
- `IsDate` 에서 `IsDateString`으로 데코레이터 변경
- 예외 메시지를 커스텀하기 위해 추가
- 토큰이 없는 경우: `message: "비로그인 상태의 요청입니다."`
- 토큰이 만료된 경우: `message: "토큰이 만료되었습니다."`
-  토큰이 유효하지 않은 경우: `message: "유효하지 않은 토큰입니다."`
- header 및 payload에 대해서만 확인하는 것으로 추정
- 이 외의 경우: `message: "Unauthorized"`
- 추가로 JwtStrategy 전략에 대한 검증 추가
- `payload`가 없거나, 올바르지 않은 `payload`이거나 `user`가 없을 경우 `401` 반환
- 이전에 `AuthGuard()`를 사용하던 부분을 `JwtAuthGuard`로 수정
1. DTO에서 받아온 일기 `uuid`를 통해 저장되어 있는 해당 …
=> [Feat] 일기 수정 API에 대한 서버 응답 수정 및 e2e 테스트 작성

BE/src/diaries/diaries.entity.ts, BE/src/shapes/shapes.entity.ts, BE/src/users/users.entity.ts
- entity에서 uuid에 대해 unique 설정
- entity에서 uuid에 대해 unique 설정
- `@Unique` 데코레이터 형식으로 통일
- diary 의 point 컬럼도 unique이어야 하지만, 현재 테스트에서 동일한 point를 추가하고 있기 때문에 추후에 다시 추가하기
close #112
=> [Fix] entity에서 uuid에 대해 unique 설정

BE/package.json, BE/src/diaries/diaries.module.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts, BE/src/shapes/shapes.module.ts, BE/src/tags/tags.repository.ts, BE/test/e2e/auth.signin.e2e-spec.ts, BE/test/e2e/diaries.create.e2e-spec.ts, BE/test/e2e/diaries.delete.e2e-spec.ts, BE/test/e2e/diaries.read-list.e2e-spec.ts, BE/test/e2e/diaries.read.e2e-spec.ts
- shape 객체가 존재하지 않을 경우 404 Not Found 에러가 되도록 수정
- e2e 테스트 실행 시 옵션 추가
- diaries.service.ts 중복된 부분 모듈화 
- 아래 코드처럼 구현된 함수를 통해 shape 객체를 받아오도록 수정
- `getShapeByUuid` 함수 내부에서 찾지 못했을 경우 Not Found 에러를 던지도록 처리
```typescript
const shape = await this.shapesRepository.getShapeByUuid(shapeUuid);
``` 
- e2e 테스트 실행 시 DB 연결이 되지 않은 문제 발생
- `--runInBand --detectOpenHandles` 옵션 추가
- `--runInBand`:  모든 테스트를 순차적으로 실행하라는 의미, 테스트 사이에 서로간의 상호작용을 방지하고자 할 때 유용
- `--detectOpenHandles`: 테스트가 끝난 후에도 여전히 열려 있는 리소스를 감지하는 데 사용
- `beforeEach`에서 `beforeAll`로 수정
- 일기 내용 암호화, 태그 엔티티 배열 가져오는 부분 모듈화
- 갑자기 테스트에서 이 경우에 대해 실패를 하고 있어요..!
- close #116
=> [Fix] shape 객체가 존재하지 않을 경우 404 Not Found 에러가 되도록 수정

BE/src/diaries/diaries.service.ts, BE/src/tags/tags.repository.ts
- 태그 찾을 때 비동기 처리로 인해 태그 생성 실패
- Promise 객체를 반환하면서 에러가 제대로 catch 되지 않아서 수정
=> [Hotfix] 태그 찾을 때 비동기 처리로 인해 태그 생성 실패

BE/package.json, BE/src/auth/guard/auth.jwt-guard.ts, BE/test/e2e/diaries.e2e-spec.ts, BE/test/int/auth.signin.int-spec.ts, BE/test/int/diaries.create.int-spec.ts, BE/test/int/diaries.delete.int-spec.ts, BE/test/int/diaries.read-list.int-spec.ts, BE/test/int/diaries.read.int-spec.ts, BE/test/int/diaries.update.int-spec.ts, BE/test/jest-int.json
- 일기 e2e 테스트 코드들을 통합 테스트 코드로 변환
- 일기 e2e 테스트 코드 작성
- 현재 작성해두었던 e2e 테스트는 e2e 테스트가 아니고 통합 테스트에 가까운 코드임
- 따라서 현재 e2e 테스트를 통합 테스트로 변환시키도록 함
- 사용자의 관점에서 테스트를 진행하도록 하는 e2e 테스트 코드 작성
- 사용자가 일기를 생성하고, 조회하고, 수정하고, 수정한 일기를 조회하고, 삭제하는 e2e 테스트 작성
- 사용자가 일기를 생성하고 삭제한 후 삭제한 일기를 조회하는 실패 e2e 테스트 작성
- 이번 주는 구현한 기능에 대해 통합 테스트, e2e 테스트만 작성하기로 합의함. 단위 테스트는 추후 학습 후 구현 예정
close #118
=> [Refactor] 일기 e2e 테스트 코드들을 통합 테스트 코드로 변환 후 일기 e2e 테스트 코드 작성

FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryReadModal.js
- 긴 일기 제목은 가로로 스크롤해서 보이도록 수정
- 리스트에서 긴 일기 제목은 hidden 처리
- 기존에는 긴 일기가 자동으로 줄바꿈되는 이슈가 있었는데, 이를 white-space: nowrap 옵션을 주어 줄바꿈되지 않도록 수정하였음.
- 추가적으로 tag에서도 같은 현상이 있었기에 tag에도 적용
close #132
=> [Fix] 긴 일기 제목 UI 수정

BE/src/auth/auth.controller.ts, BE/src/auth/dto/users.dto.ts, BE/src/auth/users.entity.ts, BE/test/int/auth.signup.int-spec.ts
- 회원가입 API 응답 수정
- 회원가입 통합 테스트 작성
- 서버가 정상적인 요청을 수락한 경우 사용자를 생성하고 204 No Content 코드를 응답
- 서버가 중복된 아이디나 이메일에 대한 요청을 받은 경우 409 Conflict를 응답
- 서버가 생성 규칙을 지키지 않는 값으로 요청을 받은 경우 400 Bad Request를 응답
- 정상 요청 시 204 No Content를 응답하는 통합 테스트 작성
- 중복된 아이디 혹은 이메일로 요청 시 409 Conflict를 응답하는 통합 테스트 작성
- 회원가입 생성 규칙을 지키지 않은 요청 시 400 Bad Request를 응답하는 통합 테스트 작성
- 빈 값을 포함한 요청 시 400 Bad Request를 응답하는 통합 테스트 작성
- 문자열이 아닌 값을 포함한 요청 시 400 Bad Request를 응답하는 통합 테스트 작성
- 21자를 초과하는 닉네임으로 요청 시 400 Bad Request를 응답하는 통합 테스트 작성
- 회원가입과 로그인 과정을 모두 포함하는 e2e 테스트 작성이 필요함
close #129
=> [Feat] 회원가입 API에 대한 서버 응답 수정 및 통합 테스트 작성

FE/src/App.js, FE/src/components/LoginModal/LoginModal.js, FE/src/components/SideBar/SideBar.js
- localStorage에 accessToken을 저장하는 로직을 구현
- localStorage에서 accessToken을 삭제하고 홈페이지로 이동시키는 로직 구현
- useLayoutEffect를 이용해 새로고침이 되었을 때 현재 localStorage에 accessToken이 존재하는지 확인하고 홈페이지 혹은 메인페이지를 띄울 지 결정하는 로직을 구현하였습니다.
- localStorage의 get, set, remove을 통해 각 상황마다 accessToken을 localStorage에서 변경하는 작업을 구현하였습니다.
- refreshToken이 구현되고 난 이후에는 로직이 다시 바뀌어야 합니다.
close #134
=> [Feat] 로그인 유지 및 로그아웃 로직 변경 구현

BE/src/auth/auth.controller.ts, BE/src/auth/auth.service.ts, BE/test/int/auth.signin.int-spec.ts, BE/test/int/auth.signout.int-spec.ts
- 로그아웃 API에 대한 응답 추가
- 통합테스트 작성
- 정상적인 요청 시 204 응답
- 토큰 검사는 `JwtAuthGuard`에서 진행
- 추후 refresh token이 추가될 것을 고려하여 service 틀 작성
- 올바른 토큰으로 요청 시 204 No Content 응답
- 유효하지 않은 액세스 토큰이 포함된 상태로 로그아웃 요청 시 401 Unauthorized 응답
- 토큰이 존재하지 않은 상태로 로그아웃 요청 시 401 Unauthorized 응답
- 추후 refresh token 기능이 추가되면 코드 로직이 추가될 예정
- 로그아웃 시 refresh token 존재 여부 확인 및 삭제 등 
- close #131
=> [Feat] 로그아웃 API에 대한 서버 응답 수정 및 통합 테스트 작성

FE/src/components/DiaryModal/DiaryDeleteModal.js, FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryReadModal.js
- 읽기 모달에 개행이 정상적으로 출력되지 않는 문제점을 수정
- 리스트 제목이 넘칠 시 말줄임표로 ...을 추가하여 UI 개선
close #143
=> [Fix] 읽기 모달 개행 문제 수정, 리스트 타이틀 넘침 시 말줄임표 추가

FE/src/App.js, FE/src/components/LoginModal/LoginModal.js, FE/src/components/SideBar/SideBar.js
- 체크하지 않고 로그인 시 sessionStorage 저장
- 체크하고 로그인 시 localStorage 저장
- 로그인 모달에서 회원가입 모달로 뷰 전환
- 로그인 상태에서 새로고침했을 때 아예 로그아웃되는 것은 비정상 상황이므로, 새로고침시 로그인은 유지되도록 하되 로그인 유지를 원할 시 localStorage에 저장하여 창을 닫았다가 다시 접속해도 접속이 되도록 하고, 체크하지 않을 시 sessionStorage에 저장하여 창을 닫으면 로그아웃되도록 로직을 변경했습니다.
- 로그인 모달에서 회원가입 버튼을 클릭 시 회원가입 뷰로 전환되도록 클릭 이벤트를 추가하였습니다.
close #142
=> [chore] 로그인 유지 박스 기능 추가, 회원가입 클릭 시 뷰 전환

BE/src/app.module.ts, BE/src/auth/auth.module.ts, BE/src/auth/guard/auth.diary-guard.ts
- privateDiaryGuard가 jwtAuthGuard의 수정으로 인해 변경된 부분을 제대로 반영
- jwtAuthGuard의 생성자가 redisClient를 받기 때문에, privateDiaryGuard의 생성자의 파라미터의 순서가 redisClient, diariesRepository 순으로 되어있어야 했다.
- AuthModule의 provider에 DiariesRepository를 넣지 않으면, AuthModule만 import하여 테스트를 진행할 때 DiariesRepository를 사용할 수 없는 문제가 발생했다. 따라서 이를 수정했다. 
- 없음
close #150 
- 관련된 이슈 번호를 close 뒤에 붙여주세요.
=> [Hotfix] privateDiaryGuard 생성자 오류 수정

BE/src/shapes/shapes.entity.ts
- Shape 엔티티의 user에 eager: true로 설정
- Shape 엔티티의 user가 lazy loading 되어 getShapeByUuid로 읽어온 Shape의 user의 userId를 읽지 못하는 문제가 발생하여 수정함.
- 없음
없음
=> [Hotfix] Shape 엔티티의 user에 eager loading 추가

FE/src/components/DiaryModal/DiaryCreateModal.js, FE/src/components/DiaryModal/DiaryReadModal.js
- ReadableStream을 img로 변환 작업
- 일기 작성의 경우 아이콘 리스트를 모두 받아온 후 각각에 대하여 ReadableStream 데이터를 요청한 다음 이를 img로 변환하는 작업을 진행
- 일기 읽기의 경우 해당 일기의 데이터를 가져온 후 shapeUuid를 이용해 데이터를 요청하고 변환하는 작업을 진행
```javascript
const { data, isLoading, isError } = useQuery(
"diary",
() => getDiary(userState.accessToken, diaryState.diaryUuid),
{
onSuccess: (_data) => {
const getPromise = () =>
fetch(`http://223.130.129.145:3005/shapes/${_data.shapeUuid}`, {
method: "GET",
headers: {
"Content-Type": "application/json",
Authorization: `Bearer ${userState.accessToken}`,
},
});
return getPromise()
.then((res) => {
const reader = res.body.getReader();
return new ReadableStream({
start(controller) {
function pump() {
return reader.read().then(({ done, value }) => {
if (done) {
controller.close();
return;
} …
```
=> [Feat] 일기 작성, 읽기 모달에 아이콘 출력을 위한 API 연동

FE/src/App.js, FE/src/atoms/diaryAtom.js, FE/src/components/DiaryModal/DiaryCreateModal.js, FE/src/components/DiaryModal/DiaryDeleteModal.js, FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryReadModal.js, FE/src/components/DiaryModal/DiaryUpdateModal.js, FE/src/components/SideBar/SideBar.js, FE/src/index.js, FE/src/pages/MainPage.js
- history API 활용
- 페이지 이동을 쉽게 할 수 있도록 구현하였습니다.
- diaryAtom 상태가 바뀔 때마다 history에 pushState하여 기록하고, 이전 버튼이나 이후 버튼을 눌러 popState될 때마다 그 기록을 탐색해 diaryAtom을 변화시키면서 페이지를 변화시키도록 구현
- 삭제 모달, 리스트 뷰의 세부적인 모달 등등에 대해서는 페이지 이동 처리하는 것이 부자연스러우므로 처리하지 않음
- 추가적으로, 생성 혹은 수정하고 있을 시 새로고침이나 다른 페이지로 이동할 때 변경사항이 저장되지 않을 수 있다는 경고 문구를 출력하도록 구현하였습니다.
- 삭제나 수정 등등 작업이 끝난 후 뒤로 이동하게 될 때 최신 정보로 업데이트가 되지 않는 현상이 있음. 수정이 필요함.
close #148
=> [Feat] history API 활용하여 이전, 이후 페이지 이동 구현

BE/src/shapes/shapes.controller.ts, BE/src/shapes/shapes.default.ts, BE/src/shapes/shapes.service.ts, BE/src/utils/e3.ts
- ncloud object storage에 업로드한 모양 이미지를 svg 파일로 교체
- 저장한 svg 파일을 기반으로, 기본 모양 15개를 commonUser에 등록
- 클라이언트가 모양 요청 시 svg string을 응답하도록 수정
- 새로 업로드한 모양 파일을 shapes.default에 등록함. 따라서 createDefaultShapes를 할 때 새로 업로드한 모양 파일이 업로드되도록 함.
- 
- getShapeFromS3 함수를 새로 구현함. 오브젝트 스토리지에서 ReadableStream을 받아서 읽은 후 SVG String을 응답하도록 함
- Service의 getShapeFileByUuid 함수에서 getFileFromS3가 아니라 getShapeFromS3를 통해 요청된 이미지의 SVG String을 받아서 리턴함
- Controller의 getShapeFilesByUuid에서 Service에서 리턴받은 SVG String을 담아 응답하도록 수정 
-  ncloud object storage에 업로드한 모양 이미지를 svg 파일로 교체했습니다. 기존에는 임시로 3개의 이미지를 올려두었고, 현재는 전체 15개의 파일을 업로드한 상태입니다.
close #163
=> [Perf] 모양 파일을 png에서 svg로 변경

BE/src/shapes/shapes.controller.ts, BE/src/shapes/shapes.repository.ts, BE/src/shapes/shapes.service.ts, BE/test/int/shape.read-list.int-spec.ts
- 현재 사용자가 사용하는 모든 모양을 목록으로 만들어 응답하는 모양 목록 API 구현
- 모양 목록 API 통합 테스트 코드 작성
- 액세스 토큰을 통해 현재 사용자를 읽어오고, 해당 사용자가 사용하는 모든 모양을 배열에 담아 응답
- commonUser가 가지고 있는 기본 모양도 배열에 포함시켜서 응답하도록 함
- 정상 요청 시 모양 uuid가 담긴 배열을 담아 200 OK 응답
- commonUser가 아닌 다른 유저가 정상 요청 시 commonUser의 모양을 읽어오는지 테스트
- 액세스 토큰 없이 요청 시 401 Unauthorized 응답
모양 목록 정상 요청
close #156
=> [Feat] 모양 목록 API 구현

FE/package-lock.json, FE/package.json, FE/src/atoms/diaryAtom.js, FE/src/components/DiaryModal/DiaryCreateModal.js, FE/src/components/DiaryModal/DiaryDeleteModal.js, FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryLoadingModal.js, FE/src/components/DiaryModal/DiaryReadModal.js, FE/src/components/DiaryModal/DiaryUpdateModal.js, FE/src/components/SideBar/SideBar.js, FE/src/pages/MainPage.js, FE/src/pages/StarPage.js
- 메인 페이지 3D 뷰 구현
- 빈 공간 더블 클릭을 통한 시점 이동
- 빈 공간 더블 클릭을 통한 일기 생성 API 연동
- 별 클릭을 통한 시점 이동
- 별 클릭을 통한 일기 조회 API 연동
https://github.com/boostcampwm2023/web08-ByeolSoop/assets/67178684/96be93d2-5f49-4c1e-b67d-87f1bd70f109
- 메인 페이지3D 뷰 구현
- 원점 (0, 0, 0)을 기준으로 하는 OrbitControls
- 카메라는 원점을 기준으로 반지름이 3인 구 위에서만 이동
- 시점 이동 시 raycasting과requestAnimationFrame을 활용
- 기존의 이미지 배경화면 대신 3D 뷰 적용
- API 연동을 위해 recoil, react-query 활용
- 일기 데이터가 최신화될 때마다 컴포넌트들에 반영하기 위해 상위 컴포넌트에서 useQuery 관리
- 모달의 상태 변화가 일어날 때마다 useQuery의 refetch를 활용하여 데이터 최신화
- 추후 디자인을 많이 바꿔야 될 것 같다.
- 시점 이동 애니메이션에 대해 연구해야 한다.
close #158
=> [Feat] 메인 페이지 3D뷰 구현 및 API 연동

.github/workflows/deploy-backend.yml, .github/workflows/deploy-frontend.yml
docker compose up 명령 실행 시 --build 옵션 제거
`docker compose up --force-recreate -d 2>log.out` 에서 --build 옵션 제거
- `build` 옵션은 Docker Compose에게 서비스에 대한 이미지를 강제로 다시 빌드하도록 지시
- pull로 받아온 이미지가 아닌 새로운 이미지를 생성함
- Dockerfile에서 어짜피 git pull을 하고 있는데 반영이 왜 안되었는지는 아직 모르겠음..!
- #165
=> [Deploy] docker compose up 명령 실행 시 --build 옵션 제거

BE/src/app.module.ts, BE/src/stat/dto/stat.tags.dto.ts, BE/src/stat/stat.controller.ts, BE/src/stat/stat.module.ts, BE/src/stat/stat.service.ts, BE/test/int/stat.service.int-spec.ts
- `/stat/tags-rank/:year` `GET` API 구현
- 해당 연도에 태그가 없거나, 태그가 적다면 1~3위가 모두 반환되지 않을 수 있음
- StatModule, Controller, Service 틀 정의
- 컨트롤러에 `@UseGuards(JwtAuthGuard)` 사용
- stat.tags.dto 정의
- `/stat/tags-rank/:year` `GET` API 구현
- year에 대한 Param을 받을 때 ParseIntPipe를 활용하여 정수 데이터로 변환
- 숫자가 아닌 문자열, 소수점에 대한 데이터 전송 시 400 Bad Request를 반환
- 태그가 없는 일기가 있어도 정상 동작
-  repository를 따로 구현하지 않고 service 단에서 DB 통신 코드 작성
- 이유: 여러 테이블을 조인하고 복잡한 집계 쿼리를 실행하는 비즈니스 로직을 수행하기 때문
- DB와 연동하는 코드를 작성하고 싶었으나, DB에 따라 테스트 결과가 달라짐
- 따라서 mocking으로 처리
- class에서 private으로 처리된 fetchTopThreeTagsByUser 함수는 mocking 불가능
- 따라서 QueryBuilder를 mocking
- 성공 응답
- year에 대한 타입 에러
- StatService의 역할이 많아질 경우, 모양과 태그 각각의 독립된 서비스로 분리하는 방향도 고민중에 있음
- `mockQueryBuilder` 타입을 `as any`로 설정한 이유
- TypeORM의 createQueryBuilder 메서드는 SelectQueryBuilder 인스턴스를 …
=> [Feat] 연도별 태그 순위 API 구현

BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts
- 감정 분석 결과가 정상적으로 저장되지 않는 오류 수정
- sentimentStatus의 양식으로 넣어야 하는 sentimentDto의 sentiment 값에 일반 string을 넣어 undefined 값이 넘어가게 됨
- 결과적으로 save시 undefined 값이 엔티티에 전송되어 기본 값인 ERROR를 저장하게 되었음
- 현재는 sentimentStatus 형식에 맞는 형태로 수정하여 정상 작동중
- 없음
없음
=> [Hotfix] 감정 분석 결과 저장 오류 수정

BE/src/app.module.ts, BE/src/diaries/diaries.controller.ts, BE/src/lines/dto/lines.dto.ts, BE/src/lines/lines.controller.ts, BE/src/lines/lines.entity.ts, BE/src/lines/lines.module.ts, BE/src/lines/lines.repository.ts, BE/src/lines/lines.service.ts, BE/src/utils/data-transform.ts
- Line Entity 생성
- 데이터 변환 함수 파일 모듈화
- 별자리선 API 구현
- 테이블명은 constellation로 지정
- 특정 유저가 사용한 별자리선 조회 구현을 위해 user 컬럼 추가
- 별자리선 soft delete 구현을 위해 deletedDate 컬럼 추가
- diariesController에서 응답 형식으로 데이터를 변환하는 코드를 `utils/data-transform.ts` 로 이동
- 별자리선 조회 응답 형식으로 변환해주는 `getReadLineDtoFormat` 함수 구현
1. 별자리선 생성
- `/lines POST`
- 정상 요청 시 201 Created 및 id 반환
- 중복된 별자리선 생성 요청 시 400 Bad Request
- 동일한 uuid 요청 시 400 Bad Request
- 존재하지 않는 별에 대해 요청 시 400 Bad Request
- 권한 에러: 401 Unauthorized
2. 별자리선 조회
- `/lines GET`
- 로그인한 유저의 별자리선 조회
- 정상 요청 시 200 OK 및 body에 `ReadLineDto[]` 타입으로 반환
- 권한 에러: 401 Unauthorized
3. 별자리선 삭제
- `/lines/:id DELETE`
- 삭제 성공 시 204 No Content
- 타인의 별자리선 삭제 요청 시 404 Not Found
- 존재하지 않는 별자리선 삭제 요청 시 404 Not Found
- 권한 에러: 401 Unauthorized
- 별자리선 생성 정상 요청
- 별자리선 생성 중복 요청
- 별자리선 조회 요청
- 별자리선 …
=> [Feat] 별자리선 Entity 생성 및 API 구현

BE/src/auth/auth.controller.ts, BE/src/auth/auth.service.ts
- 만료된 액세스 토큰으로 요청 시 성공하도록 수정
- 액세스 토큰이 아니라 헤더에서 사용자 아이디를 추출함으로써 만료된 액세스 토큰으로 요청 시 성공하도록 수정
- 기존에는 만료된 액세스 토큰에서 사용자 아이디 추출을 시도하여, 사용자 아이디가 undefined가 된 상태로 새로운 액세스 토큰이 발급되었다. 따라서 새로 발급된 액세스 토큰을 사용하면 사용자 아이디를 읽을 수 없는 문제가 있었다.
- 없음
없음
=> [Hotfix] 만료된 액세스 토큰으로 요청 시 성공하도록 수정

BE/src/diaries/diaries.module.ts, BE/src/diaries/diaries.repository.ts
- 일기를 삭제할 경우 해당 일기와 연결된 별자리선을 모두 찾아 soft remove 실행
- `onDelete` 옵션은 현재 soft remove를 하고 있어 제대로 동작하지 않음
>  https://yescoding.tech/backend/type-orm-soft-delete-cascade_en
- 원래 위 링크처럼 `cascade: ['soft-remove']` 옵션을 통해 삭제를 시도하였으나 ManyToOne(Line Entity)에 추가할 경우 라인이 삭제될 때 일기가 삭제됨
- Diary 엔티티에서 Line 엔티티로의 OneToMany 관계를 정의하고, 이 관계에 `cascade: ['soft-remove']` 옵션을 지정해보았으나 동작하지 않음
- Line 엔티티가 두 개의 Diary 엔티티를 참조하고 있어 동작하지 않을수도 있다고 함
- 따라서 Diary가 삭제될 때 Line 엔티티에서 해당 Diary를 참조하는 모든 레코드를 찾아서 soft delete하는 로직을 추가
- 현재 일기 삭제 후 새로고침 전까지 화면에 별자리선이 남아있게되어서 FE에 처리 필요
- 태그도 ManyToMany라 직접 삭제를 구현해야 할 것 같아 현재는 추가하지 않음
- #178
=> [Hotfix] 별자리선이 연결된 일기 삭제 시 별자리선도 함께 삭제

BE/src/diaries/diaries.service.ts
- 일기의 content에서 앞 뒤 공백을 제거
- trim 메서드를 통해 일기의 content에서 앞 뒤 공백을 제거함
- 공백은 줄바꿈, 탭, 공백을 의미함
- 없음
close #202
=> [Fix] 일기 생성, 수정 시 Content 관련 오류 수정

BE/package-lock.json, BE/package.json, BE/src/auth/auth.controller.ts, BE/src/auth/auth.module.ts, BE/src/auth/auth.service.ts, BE/src/auth/strategies/jwt.strategy.ts, BE/src/auth/strategies/naver.strategy.ts, BE/src/auth/users.entity.ts, BE/src/utils/enum.ts
- 네이버 로그인 전략 구현
- 네이버 OAuth 콜백 API 구현
- passport-naver-v2 라이브러리를 설치해서 NaverOAuthStrategy 구현
- 생성자를 통해 인증 서버에 액세스 토큰, 리프레시 토큰, 프로필 정보를 요청한다.
- NaverOAuthStrategy의 validate에서 네이버 아이디 프로필의 정보를 가공해서 User 객체에 저장함
- /auth/naver/callback GET 요청 시 NaverOAuthStrategy를 통해 프로필 정보가 가공된 User 객체를 받음
- 해당 User 객체가 존재하지 않는 경우 새로 데이터베이스에 저장함
- 기존 로그인 과정과 동일하게 액세스 토큰을 발급하고 리프레시 토큰을 Redis에 저장한 후 액세스 토큰을 201 Created와 함께 응답함
- 현재는 네이버 로그인으로 byeolsoop08 아이디만 로그인 가능해요. 추가로 네이버 아이디 로그인 해보고 싶으시면 저한테 말씀해주시면 아이디 등록해서 로그인할 수 있게 만들겠습니다.
close #200
=> [Feat] 네이버 로그인

BE/package-lock.json, BE/package.json, BE/src/auth/strategies/naver.strategy.ts
- passport-kakao와의 충돌을 피하기 위해 passport-naver의 버전을 구버전으로 사용
> PR 올리기 전/후 아래 내용을 확인하고 지우세요!
- PR 템플릿 제목이 [기능명] PR 제목의 형식을 갖추고 있는지 확인
- 브랜치 이름이 {기능명}/{issue-number}-{feature-name}의 형식을 갖추고 있는지 확인
- PR 후 conflict가 나지 않는지 확인 (충돌 시 해결 필수)
- merge 이후 브랜치에 해당하는 issue가 closed 되었는지 확인
- passport-naver 버전 낮추기
- passport-kakao와의 충돌을 피하기 위해 최신의 passport-naver-v2 대신 passport-naver를 사용 
- passport-oauth 라이브러리가 passport-kakao에서는 1.1.2 이하를, passport-naver-v2에서는 1.5.0 이상을 원했기 때문에 passport-naver 쪽을 다운그레이드 했습니다.
없음
=> [Chore] passport-naver 버전 낮추기

BE/src/app.module.ts, BE/src/auth/users.entity.ts, BE/src/purchase/dto/purchase.design.dto.ts, BE/src/purchase/purchase.controller.ts, BE/src/purchase/purchase.entity.ts, BE/src/purchase/purchase.module.ts, BE/src/purchase/purchase.repository.ts, BE/src/purchase/purchase.service.ts, BE/src/utils/enum.ts
- Purchase 기능 초기 작업
- 유료 디자인 구매 API 구현
- Purchase 엔티티를 작성하여 MySQL DB에 purchase 테이블 생성
- Purchase 엔티티의 속성을 위한 domainEnum, designEnum 작성. 
- Purchase 도메인을 위한 PurchaseModule을 작성하고 AppModule에 Import함
- /purchase/design POST 요청에 대한 유료 디자인 구매 API를 구현
- 현재 사용자가 보유한 별가루가 부족하거나, 이미 해당 디자인을 구매한 경우 400 Bad Request 응답
- 추후 도메인이나 디자인이 추가될 경우 Enum에 추가하도록 확장성 고려함
- 테스트 코드는 현재 PR이 머지되면 네이버 로그인 API와 동시에 작성 예정
#205
=> [Feat] 유료 디자인 구매 API 구현

FE/src/components/DiaryModal/DiaryListModal.js, FE/src/components/DiaryModal/DiaryReadModal.js, FE/src/pages/MainPage.js
- 별 미리보기 색상 구현
- 감정별로 별에 색상을 도입
- 리스트 보기 타이틀 꾸미기
- 리스트 보기 타이틀에 별 미리보기와 태그 리스트 추가
- svg에 className이 붙어 있어 같은 색상을 공유하던 문제를 발견
- 데이터베이스에 등록되는 svg 데이터 자체를 깔끔하게 변경하는 방식으로 해결
- 각 별 미리보기마다 색상을 적용하여 어느 별의 형태로 일기가 저장되어 있는지 확인 가능
close #214
=> [Feat] 별 미리보기 색상 구현 + 리스트 보기 타이틀 꾸미기

BE/package.json, BE/src/purchase/dto/purchase.design.dto.ts, BE/test/int/auth.service.int-spec.ts, BE/test/int/purchase.service.int-spec.ts, BE/test/jest-unit.json, BE/test/unit/auth-credential.dto.unit-spec.ts, BE/test/unit/diaries.dto.unit-spec.ts, BE/test/unit/purchase.design.dto.unit-spec.ts, BE/test/unit/users.dto.unit-spec.ts
- 유료 디자인 구매 관련 테스트 코드 작성
- 네이버 로그인 관련 테스트 코드 작성
- PurchaseService의 purchaseDesign 메서드 통합 테스트
- PurchaseDesignDto 단위 테스트
- AuthService의 naverSignIn 메서드 통합 테스트
- 이전에 API만 먼저 PR 머지를 시키고 못썼던 테스트 코드를 작성한 PR
- 몇몇 테스트나 엣지 케이스의 경우 테스트 DB 초기화 기능의 부재로 현재 구현하기 매우 어렵거나 번거로워, 추후 테스트 DB 초기화 및 독립 환경 구축 시도 시 일괄적으로 수정 예정
close #216
=> [Test] 네이버 로그인, 유료 디자인 구매 관련 테스트 코드 작성

BE/src/auth/auth.module.ts, BE/src/auth/auth.service.ts, BE/src/auth/dto/auth-access-token.dto.ts
- 로그인 API 수정
- 로그인 API의 응답에 현재 사용자의 nickname을 같이 보내도록 수정
- 이를 위해 AccessTokenDto에 nickname 추가
- createUserTokens 메서드의 파라미터로 nickname을 추가하여 AccessTokenDto에 넣도록 함. 이를 위해 createUserTokens를 사용하는 모든 메서드에서 nickname을 넣어서 호출하도록 수정
- expiresIn 옵션이 AuthModule과 AuthService에 중복적으로 들어갔기 때문에, AuthModule의 expiresIn 옵션을 제거함
- AuthModule에서 사용하는 expiresIn 옵션은 모든 JWT 토큰에 적용되기 때문에 액세스 토큰과 리프레시 토큰에 대한 다른 옵션을 적용할 수 없어 제거함
- createUserTokens에 user 객체를 그대로 넘겨서 메서드 안에서 userId와 nickname을 풀어서 넣는 방법과 지금처럼 userId와 nickname값을 넘기는 방법 중 뭐가 더 좋을지 모르겠네요...
close #220
=> [Refactor] 로그인 API 응답 수정 및 리팩토링

BE/src/auth/users.repository.ts, BE/src/diaries/diaries.module.ts, BE/src/diaries/diaries.repository.ts, BE/src/diaries/diaries.service.ts, BE/src/purchase/purchase.controller.ts
- 별가루 조회 API 구현
- 새 일기 작성 시 30 별가루 적립
- `/purchase/credit` GET 요청 시 credit 반환 및 200 OK 응답
- 아래 함수를 통해 현재 작성되는 일기가 새로운 일기인지 확인
- createdDate를 조건으로 검사 (실제 일기 저장 시간 기준)
- soft delete된 일기도 포함하여 별가루 적립 남용 방지
- new. Date(), mysql 검사 모두 UTC 기준으로 실행
```ts
async getDiaryByToday(userId: string): Promise<Diary[]> {
const currentDate = new Date();
const [year, month, date] = [
currentDate.getFullYear(),
currentDate.getMonth(),
currentDate.getDate(),
];
const startDate = new Date(year, month, date, 0, 0, 0, 0);
const endDate = new Date(year, month, date, 23, 59, 59, 999);
const diaryList = await Diary.find({
where: { user: { userId }, createdDate: Between(startDate, endDate) },
withDeleted: true,
});
return diaryList;
}
``` 
- 결제 모듈을 적용할 수 없어 일기 작성 시 별가루 30개 적립
- 임시로 30개로 적용
- 테스트 코드 추후 작성 필요
close …
=> [Feat] 새 일기 작성 시 별가루 적립 및 조회 API 구현

BE/src/auth/auth.service.ts, BE/src/auth/guard/auth.jwt-guard.ts
- 클라이언트 IP를 환경에 따라 다르게 받도록 수정
- 현재 환경이 배포 환경인 경우 x-forwarded-for 헤더에서 IP를 받도록 함
- 현재 환경이 개발 환경인 경우 그대로 request.ip에서 IP를 받도록 함
- 이러한 수정 사항을 authService와 JwtAuthGuard에 적용
- [개발일지](https://www.notion.so/byeolsoop/NGINX-IP-f7ecd6e6b6c14e7d9e015f9ae365bd86?pvs=4)
close #256
=> [Fix] 클라이언트 IP를 환경에 따라 다르게 받도록 수정

FE/src/components/DiaryModal/DiaryListModal.js
- 리스트 보기에서 수정 시도 시 별이 원점으로 가는 이슈 수정
- 원인을 찾아보니 리스트 보기에서는 일기를 선택할 때 point가 100000이 곱해지지 않는 이슈가 있었음
- refetch에서 100000을 나누는 로직이 있어 원점에 생성된다고 느낀 것이지, 원점은 아니었다!
- 100000을 곱해서 diaryState에 저장하니 문제 해결
- Cannot assign to read only property 'x' of object '#<Object>' 에러가 발생했었기에 이 문제도 따로 처리해야되나 싶었는데, 이유는 모르겠으나 동시에 처리됨. 이후 확인 요망
close #251
=> [Fix] 리스트 보기에서 수정 시도 시 별이 원점으로 가는 이슈 수정

FE/src/components/DiaryModal/DiaryAnalysisModal.js, FE/src/components/DiaryModal/DiaryListModal.js
- 리스트 보기 달력 크기 버그 수정
- 통계 페이지 잔디 크기 구현 방식 수정
- 리스트 보기 달력 크기가 각 월에 따라 유동적으로 변동하지 않아 어색하게 보이는 부분 수정
- 통계 페이지 잔디 크기가 비정상적으로 작게 보이는 부분 수정
없음
=> [Fix] 리스트 보기 달력 크기 버그 수정, 통계 페이지 잔디 크기 구현 방식 수정

BE/src/auth/guard/auth.jwt-guard.ts
- 샘플 계정 중복 로그인 허용
- 아이디가 "sample"일 시 리프레시 토큰 검사를 하지 않고 중복 로그인을 허용하도록 수정
- 발표 상황에서 sample에 대한 중복 로그인 시 403 오류가 발생하는 것을 방지하기 위한 수정 사항
close #274
=> [Feat] 샘플 계정 중복 로그인 허용
