.gitignore
BE/.eslintrc.js
BE/.prettierrc
BE/package-lock.json
BE/package.json
FE/.eslintrc.js
FE/.prettierrc
FE/package-lock.json
FE/package.json

- ESLint + prettier 추가
- VSCode에서 개발할 때 포맷을 고정하기 위해 ESLint와 prettier 환경설정을 진행하였습니다.
- FE, BE 별로 추가적인 환경설정이 필요
- BLSP-22

Feat: VSCode ESLint + prettier 설정 추가

---

.gitignore
BE/package-lock.json
BE/package.json
BE/src/configs/typeorm.config.ts
BE/src/users/users.dto.ts
BE/src/users/users.entitiy.ts
BE/src/utils/enum.ts

- dotenv 모듈을 활용하여 환경변수 설정
- User Entity 및 DTO 생성
- `.env` 파일 생성 및 `gitignore` 목록 추가
- `typeorm.config.ts` 파일에 환경변수 추가
- premium 컬럼에 대한 enum 추가
- `class-validator`를 활용하여 DTO 유효성 검사
close #13

[Feat] User Entity 및 DTO 생성

---

FE/src/atoms/diaryAtom.js
FE/src/components/DiaryModal/DiaryModal.js
FE/src/components/LoginModal/LoginModal.js
FE/src/pages/HomePage.js

- 일기 생성 모달 UI 구현
- 모달 상태 관리를 위한 DiaryAtom 추가
- 일기 생성 모달 UI 구현
- 배경 클릭 시 일기 생성 모달 표시 이벤트 추가
- 중복되는 컴포넌트 최소화 필요
close #22

[Feat] 일기 생성 모달 UI 구현

---

FE/src/components/DiaryModal/DiaryModal.js
FE/src/components/LoginModal/LoginModal.js
FE/src/components/SignUpModal/SignUpModal.js
FE/src/styles/ModalButton.js
FE/src/styles/ModalInputBox.js
FE/src/styles/ModalTitle.js
FE/src/styles/ModalWrapper.js

- 로그인 UI 디자인 수정
- 중복 CSS 모듈화
- 로그인 UI 디자인 수정
- 로그인 / 회원가입, 일기 생성 모달에 쓰이는 중복 CSS 모듈화 (ModalWrapper, ModalTitle, ModalInputBox, ModalButton)
- 모듈화한 컴포넌트 적용
- 아직 중복된 부분이 남아있는데 팀원 분들과 이야기해보고 추가 모듈화할 생각입니다.
close #24

[Chore] 로그인 UI 디자인 수정

---

BE/src/diaries/diaries.entity.ts
BE/src/shapes/shapes.entity.ts
BE/src/tags/tags.entity.ts
BE/src/users/users.entity.ts

- 모양, 태그 엔티티 생성
- 유저 엔티티 FK로 추가
- 일기 엔티티에 FK 연결
| 참고: https://orkhan.gitbook.io/typeorm/docs/many-to-many-relations
- 일기 엔티티와 `ManyToMany` 관계 생성 
- DTO는 추후 필요 시 추가
close #29

[Feat] 모양, 태그 엔티티 생성

---

.github/workflows/deploy.yml

- FE 배포 코드에서 한번 더 pull하는 문제 수정
- FE 배포 코드에서 한번 더 git pull origin main을 요청하는 문제로 인해 BE 서버 실행 중 pull이 되어 서버가 종료되는 오류가 발생했다.
- 없음
close #50

[Fix] FE 배포 코드 오류 수정

---

FE/src/atoms/diaryAtom.js
FE/src/components/DiaryModal/DiaryCreateModal.js
FE/src/components/DiaryModal/DiaryDeleteModal.js
FE/src/components/DiaryModal/DiaryReadModal.js
FE/src/pages/MainPage.js

- 일기 삭제 모달 UI 구현
- 삭제 모달 ON / OFF 를 위한 상태 관리
- 일기 삭제 모달 UI 구현
- 디자인 수정 필요함
close #55

[Feat] 일기 삭제 모달 UI 구현

---

BE/package-lock.json
BE/package.json
BE/src/app.module.ts
BE/src/introduce/introduce.controller.ts
BE/src/introduce/introduce.module.ts
BE/src/introduce/introduce.service.ts
BE/src/utils/e3.ts

- 클라우드 스토리지 기능을 담은 E3 모듈 구현
- /introduce GET 요청을 처리하는 API 구현
- NCP Object Storage에 버킷을 생성했습니다. 이 버킷에 여러 파일을 저장할 수 있습니다.
- aws-sdk 모듈을 사용하여 NCP Object Storage를 Amazon S3를 사용하는 것과 동일한 API로 제어할 수 있습니다.
- utils 디렉토리의 e3.ts 모듈을 만들어 NCP Object Storage와 관련된 코드를 작성하도록 했습니다.
- NCP Object Storage의 파일의 readStream을 생성하는 getFileFromS3 함수를 구현했습니다.
- 소개 페이지에 대한 API를 다루는 introduce 디렉토리와 introduce.module.ts를 구현했습니다.
- introduce.controller에서 /introduce GET 요청을 받아 처리합니다.
- introduce.service에서 e3.ts 모듈의 getFileFromS3 함수를 통해 readStream을 받아 클라이언트에 전달하게 됩니다.
- 추후 소개 페이지 영상이 실제로 제작되면 클라우드 스토리지에 업로드하고 코드 수정이 필요합니다.
- e3.ts에 모양 이미지를 저장할 때 사용할 수 있는 코드를 주석 처리하여 업로드했습니다. 추후 모양 기능 구현 시 활용 예정입니다. 
close #57

[Feat] 소개 페이지 영상 API 구현

---

BE/src/diaries/diaries.service.ts

- 일기 생성, 수정 시 AES-256-CDC를 통한 일기 내용 암호화
- 일기 조회 시 AES-256-CDC를 통한 일기 내용 복호화
- user.service.ts의 일기 생성, 수정 메서드에 aes-256-cbc를 통한 암호화 코드 추가
- user.service.ts의 일기 읽기, 일기 목록 읽기에 aes-256-cbc를 통한 복호화 코드 추가
- 현재는 동일한 Key와 IV를 .env에 저장해서 사용하고 있음. 그러나 권장 사항으로는 동일한 Key를 사용해도 IV를 다르게 해주어야 한다고 함.
- .env를 유출되지 않게 관리하는 경우 괜찮다고 하나, 필요하다고 생각되는 경우 IV를 diary DB 테이블에 칼럼으로 추가하는 방안도 고려 필요
close #101

[Feat] 일기 내용 암호화 기능 추가

---

FE/src/App.js
FE/src/atoms/diaryAtom.js
FE/src/components/DiaryModal/DiaryCreateModal.js
FE/src/components/DiaryModal/DiaryListModal.js
FE/src/components/DiaryModal/DiaryLoadingModal.js
FE/src/components/DiaryModal/DiaryReadModal.js
FE/src/components/DiaryModal/DiaryUpdateModal.js
FE/src/pages/MainPage.js

- 일기 수정 모달 추가
- 기존 일기 데이터 요청 및 모달에 반영
- 수정된 내용 저장 시 서버에 PUT 요청
- 커스텀 스크롤바 추가
- line-height 개선, 폰트 사이즈 개선
- 일기 생성 모달을 활용하되 약간은 변형하여 일기 수정 모달을 구현하였습니다.
- PUT 요청을 해야 하기 때문에 따로 구현하였습니다.
- 일기를 수정하고 저장을 누르면 PUT 요청을 보내고 저장할 수 있습니다.
- 수정 요청 시 SyntaxError: Unexpected end of JSON input 이라고 콘솔에 에러가 발생하는데, 기능적으로는 정상작동하고 있기에 일단 올립니다.
close #108

[Feat] 일기 수정 api 연동, 커스텀 스크롤바 추가, 가독성 개선

---

FE/src/components/DiaryModal/DiaryCreateModal.js
FE/src/components/DiaryModal/DiaryDeleteModal.js
FE/src/components/DiaryModal/DiaryListModal.js
FE/src/components/DiaryModal/DiaryReadModal.js
FE/src/components/DiaryModal/DiaryUpdateModal.js
FE/src/components/SideBar/SideBar.js
FE/src/styles/Modal/ModalWrapper.js

- UI 애니메이션 추가
https://github.com/boostcampwm2023/web08-ByeolSoop/assets/67178684/a285f693-8c07-4ed8-a3d2-963ff9a36162
- 모달 등장 애니메이션
- 아이콘 호버 애니메이션
close #113

[Feat] UI 애니메이션 추가

---

FE/src/components/DiaryModal/DiaryListModal.js
FE/src/components/DiaryModal/DiaryReadModal.js
FE/src/components/DiaryModal/DiaryUpdateModal.js

- 로딩 시 div로 되어있는 부분 일괄 수정
- 일기 로딩 시 div 형식으로 리턴하고 있어 스크롤바가 생기면서 화면이 깜빡이는 이슈를 해결
- 모든 로딩 상황에 대해 로딩 시 modalwrapper에서 로딩 문구를 출력하도록 하여 해결하였음
close #119

[Fix] 로딩 시 화면 깜빡임 수정

---

FE/src/components/DiaryModal/DiaryListModal.js

- 모달 오른쪽 부분 빈 공간 삭제
- absolute left를 없애고 padding 추가

[Fix] 모달 오른쪽 부분 빈 공간 삭제

---

FE/src/App.js
FE/src/components/DiaryModal/DiaryReadModal.js
FE/src/components/SideBar/SideBar.js

- 일기 쓰기 모드로 변환 시 일기 조회 모달 닫기
- 반응형 UI 수정

[Fix] 반응형 UI 수정

---

BE/src/auth/users.repository.ts

- Conflict Exception 오류 수정
- Conflict 발생 시 아이디, 이메일 둘 중 어떤 것으로 발생해도 무조건 아이디로 메세지가 가는 오류 수정
- 없음
#129

[Hotfix] Conflict Exception 오류 수정

---

FE/src/components/DiaryModal/DiaryUpdateModal.js
FE/src/components/SignUpModal/SignUpModal.js
FE/src/styles/Modal/ModalInputBox.js

- 회원가입 아이디 입력 박스 UI 추가
- 회원가입 API 연동
https://github.com/boostcampwm2023/web08-ByeolSoop/assets/67178684/32cd4fde-4417-4030-aada-f1722767d168
- 204 코드에 대해 json() 삭제
- 이외 코드에 대해 json() 실행
- 서버에서 보내주는 오류 메세지를 비동기 처리를 해줘야 한다는 걸 알았음!
- 추후 코드 리팩토링 필요
close #130

[Feat] 회원가입 API 연동

---

BE/src/diaries/diaries.repository.ts
BE/src/diaries/diaries.service.ts

- 일기 목록 오류 수정
- 일기 목록 요청 시 모든 유저의 일기를 읽어오는 오류 수정
- 없음
없음

[Hotfix] 일기 목록 오류 수정

---

FE/.eslintrc.js

- 서버 접속 시 eslint 오류 해결
- eslint 설정에서 경로 수정

[Hotfix] eslint 오류 해결

---

.github/workflows/deploy-backend.yml
.github/workflows/deploy-frontend.yml

ssh 접속 후 도커 재시작 스크립트 수정
- `docker-compose.yml` 파일이 위치한 경로에서 명령을 실행하도록 수정
- 이미지가 pull이 되지 않고 있었음
- `docker system prune -f`를 통해 사용하지 않고있는 이미지만 삭제 및 -f 옵션으로 확인하지 않고 바로 명령 실행
- #165

[Deploy] ssh 접속 후 도커 재시작 스크립트 수정

---

FE/src/pages/MainPage.js

- 기존에 기본 모양 API를 긁어오던 걸 사용자별 전체 모양 API에서 가져오는 것으로 변경했습니다.
- 없음!
close #175

[Fix] 사용자별 전체 모양 API로 변경

---

FE/src/pages/MainPage.js

- 403 에러 시 홈페이지로 자동 리다이렉션
- 403 에러 시 홈페이지로 리다이렉션 되도록 수정
- 윈도우 변경될 때 자동으로 체크하도록 수정
- 없음

hotfix: 403 에러 시 홈페이지로 리다이렉션

---

FE/src/components/DiaryModal/DiaryCreateModal.js
FE/src/components/DiaryModal/DiaryDeleteModal.js
FE/src/components/DiaryModal/DiaryUpdateModal.js

- 일기 수정 버그 고치기 위해 롤백
- 일기 수정 버그 고치기 위해 롤백

[hotfix] 일기 수정 버그 고치기 위해 롤백

---

FE/src/components/DiaryModal/DiaryReadModal.js
FE/src/pages/StarPage.js

- 일기 생성 모드에서 편집 모드 전환 시 에러 수정
https://github.com/boostcampwm2023/web08-ByeolSoop/assets/67178684/67bd116a-e643-4dbe-b5ad-47768b1702b5
- 일기 CRUD 모달이 닫히지 않은 채 편집 모드로 넘어가는 에러가 존재
- 모달 상태 관리 로직을 추가해 모달을 닫고 넘어가도록 변경

[Fix] 편집 모드 전환 시 모달이 닫히도록 수정

---

FE/src/components/LoginModal/LoginModal.js
FE/src/components/SignUpModal/SignUpModal.js

- 회원가입 아이디 비밀번호 규칙 안내
- 시도 시 아이디 및 비밀번호 규칙에 어긋날 경우 에러 메시지로 해당 부분 안내메시지 출력
- 로그인 규칙 어길 시 오류 메시지 통일화
- 서버에서 검사했을 경우의 오류 메시지와 동일하게 변경
- 회원가입 시도 시 출력되던 에러메시지에 추가적으로 안내 메시지를 출력하도록 하였습니다.
- 로그인 규칙 어길 시 오류 메시지가 서버에서 리턴되던 오류 메시지와 동일하도록 변경하였습니다.
- 추가적으로, 로그인 시도 시 엔터로 바로 로그인할 수 있도록 추가하였습니다.
close #193

[Chore] 회원가입 규칙 안내 및 로그인 규칙 어길 시 오류 메시지 통일화

---

FE/src/components/DiaryModal/DiaryAnalysisModal.js

- 일기 월별 통계 집계 시 작성 수가 아닌 작성 일수로 계산하던 오류 해결

[Fix] 일기 월별 통계 오류 해결

---

BE/src/auth/strategies/naver.strategy.ts

- passport-naver로 수정되면서 profile 반환 형식이 변경된 것으로 추정됨
- #200

[Hotfix] naverStrategy profile 파싱 변경

---

FE/src/components/DiaryModal/DiaryCreateModal.js

- 태그 입력 시 마지막 글자 중복 입력 오류 해결
- 엔터 버튼은 keypress로 감지

[Hotfix] 태그 입력 시 마지막 글자 중복 입력 오류 해결

---

BE/src/auth/auth.controller.ts
FE/src/App.js

- NGINX에서 OAuth 2.0 로그인 시 CORS가 발생하는 에러 수정
- 자세한 변경 사항은 개발 일지에 작성하겠습니다.
- 없음
없음

[Hotfix] CORS 에러 수정

---

FE/src/pages/LoadingPage.js

[Fix] 개발 서버 로그인 에러 해결

---

FE/src/components/PurchaseModal/PurchaseModal.js

[Fix] 결제 페이지 알럿창 추가

---

.github/workflows/deploy-frontend.yml

- 프론트엔드 배포 시 빌드 후 NGINX를 활용하여 정적 파일을 서빙하도록 설정
- github secret에 저장되어있는 환경변수를 파일로 저장
- 환경변수 저장 시 특정 변수를 명령어로 인식하여 따옴표로 하나의 문자열로 변경
- [이전 commit](https://github.com/boostcampwm2023/web08-ByeolSoop/commit/21b9dcc649731964ccdd45d3d6d9f2f0aadee9d1)
- [개발 일지](https://byeolsoop.notion.site/FE-NGINX-d3225ec2cbe2402ca3d02773c9d274f1?pvs=4)
close #249

[Deploy] 환경변수 저장 실패 hotfix

---

BE/src/utils/enum.ts

- 유료 디자인 enum 수정
- 유료 디자인을 땅의 색상 바꾸기에서 모양 바꾸기로 기획을 변경함
- 따라서 변경된 기획에 맞춰 유료 디자인 enum 값을 변경함
- 없음
close #258

[Chore] 유료 디자인 enum 수정

---

FE/src/atoms/diaryAtom.js
FE/src/components/DiaryModal/DiaryAnalysisModal.js
FE/src/components/DiaryModal/DiaryCreateModal.js
FE/src/components/DiaryModal/DiaryDeleteModal.js
FE/src/components/DiaryModal/DiaryReadModal.js
FE/src/components/DiaryModal/DiaryUpdateModal.js
FE/src/components/DiaryModal/EmotionIndicator/DiaryEmotionIndicator.js
FE/src/components/ModalBackground/ModalBackground.js
FE/src/components/SignUpModal/SignUpModal.js
FE/src/pages/MainPage.js
FE/src/pages/Redirection.js
FE/src/pages/StarPage.js
FE/src/utils/utils.js

- 403 에러 발생 시 알럿창을 띄우도록 되어있었는데, 해당 로직이 각 fetch마다 중첩되어있어 하나의 알럿창의 확인을 클릭해도 다른 알럿창이 다시 켜지고, 이를 누르면 다른 알럿창이 다시 켜지는 등의 체이닝 현상이 있었음
- 해당 부분을 로그아웃 안내 리다이렉션 관련 모달창을 띄우는 것으로 로직 변경하여 해결.
close #265

[Fix] 403 에러 시 무한 알럿 발생 버그 수정

---

FE/src/components/DiaryModal/DiaryAnalysisModal.js
FE/src/components/DiaryModal/DiaryListModal.js
FE/src/components/PurchaseModal/PurchaseModal.js
FE/src/components/SideBar/SideBar.js
FE/src/components/SignUpModal/SignUpModal.js
FE/src/styles/Modal/ModalInputBox.js

- Refactor
- 반복 작성된 컴포넌트는 고차함수를 활용하여 반복
- attribute는 리스트로 분리하여 정리
- Refactor
- 반복 작성된 컴포넌트는 고차함수를 활용하여 반복
- attribute는 리스트로 분리하여 정리
- Starpage의 경우 건드리지 않음 (건드렸다가 터질 수도 있다고 간주)
close #268

[Refactor] 컴포넌트 중복 요소 분리 및 정리

---

FE/src/pages/StarPage.js

- 별 이동 안 되는 문제 수정
- 리팩토링하면서 사용하지 않는 변수를 지우다가 생긴 버그 해결

[Hotfix] 별 이동 안 되는 문제 수정
